services:
  dev:
    image: molaccessdev
    build:
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /opt/workdir
    stdin_open: true
    tty: true
    command: /bin/sh -c "nix develop"