services:
  dev:
    image: molaccess/mingw:latest
    build:
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ../../../../.
        target: /opt/workdir
      - type: bind
        source: ../../../../installdir
        target: /opt/installdir