name: "Main"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install swig cmake clang python3 python3-dev python3-pip
        pip --no-input install tinydb
    - name: Build
      run: |
        cmake -B target/release -D CMAKE_BUILD_TYPE=Release -D MOLACCESS_BUILD_TESTS=ON
        cmake --build target/release -j$(nproc)
    - name: Sanity check
      run: |
        cd target/release/tests
        ./sanity
        ./route
        cd ../
    - name: Python Client/Server (Integration Tests)
      run: |
        cd tests/python
        python3 server.py &
        python3 client.py
    - name: molaccessd & molmessg (Integration Tests)
      run: |
        # To do: Make this run `run_message_test.sh`
        python3 molaccessd_test.py &
        python3 molmessg_test.py -c 'SEND ANNOUNCE connection_route=announcetest resource_collection=Molecular:Default'
        python3 molmessg_test.py -c 'SEND CREATE resource_name=Name resource_value=Value resource_value_default=DefaultValue resource_value_type=string'