name: "MinGW (Docker Compose)"
on:
  pull_request:
  push:
jobs:
  compose-alpine-mingw:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - uses: docker/setup-compose-action@v2
    - name: Run using Docker Compose
      run: ./misc/integration/tasks/ci_compose.sh alpine/mingw
    - uses: actions/upload-artifact@v7
      with:
        path: installdir
        name: MinGW build artifact